// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQkBtpoNZjES_SCgkwkUAHl-rxX0PgT0',
    appId: '1:24137969618:web:c1abe056128bc9a7a6620b',
    messagingSenderId: '24137969618',
    projectId: 'tax-payer-services-baf97',
    authDomain: 'tax-payer-services-baf97.firebaseapp.com',
    storageBucket: 'tax-payer-services-baf97.firebasestorage.app',
    measurementId: 'G-5MFSF53YN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCenexFvGhu65RVe6b7VtVPyn9Ya-CsWOU',
    appId: '1:24137969618:android:422c0d0ceece7de7a6620b',
    messagingSenderId: '24137969618',
    projectId: 'tax-payer-services-baf97',
    storageBucket: 'tax-payer-services-baf97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAoPpayem3j4R_Qkp_DMX1ztb9DtTGnh8',
    appId: '1:24137969618:ios:ab8d935077a5d735a6620b',
    messagingSenderId: '24137969618',
    projectId: 'tax-payer-services-baf97',
    storageBucket: 'tax-payer-services-baf97.firebasestorage.app',
    iosBundleId: 'com.example.marchantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAoPpayem3j4R_Qkp_DMX1ztb9DtTGnh8',
    appId: '1:24137969618:ios:ab8d935077a5d735a6620b',
    messagingSenderId: '24137969618',
    projectId: 'tax-payer-services-baf97',
    storageBucket: 'tax-payer-services-baf97.firebasestorage.app',
    iosBundleId: 'com.example.marchantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfQkBtpoNZjES_SCgkwkUAHl-rxX0PgT0',
    appId: '1:24137969618:web:3c94649944ba87f0a6620b',
    messagingSenderId: '24137969618',
    projectId: 'tax-payer-services-baf97',
    authDomain: 'tax-payer-services-baf97.firebaseapp.com',
    storageBucket: 'tax-payer-services-baf97.firebasestorage.app',
    measurementId: 'G-KLR62QN7PM',
  );
}
